const initialEquipmentData = [
    {
        "Code": "FA03A21450",
        "Equipment": "AIR COMPRESSOR 300 ~ 450 CFM (300 CFM)",
        "TotalMCHrs": 0.85,
        "TotalNoOfDays": 0.11,
        "TotalNoOfMonths": 0.00,
        "MonthlyRent": 180000,
        "RatePerHr": 692.31,
        "ConsumptionPerLtrMCHrs": 5.00,
        "TotalFuelInLtr": 4.25,
        "TotalAmount": 1053.75
    },
    {
        "Code": "FA02A00060",
        "Equipment": "ASPHALT MIXING PLANT CAPACITY 60 T/H",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 1250000,
        "RatePerHr": 4807.69,
        "ConsumptionPerLtrMCHrs": 0,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A15018",
        "Equipment": "ASPHALT PAVER VOGELE 1800 / EQUIVALENT",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 975000,
        "RatePerHr": 3750.00,
        "ConsumptionPerLtrMCHrs": 12.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A16004",
        "Equipment": "BITUMEN DISTRIBUTOR 4000 LTR-HANTA FD 3 HGA",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 180000,
        "RatePerHr": 692.31,
        "ConsumptionPerLtrMCHrs": 12.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B22040",
        "Equipment": "BULLDOZER D4 / EQUIVALENT",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 300000,
        "RatePerHr": 1153.85,
        "ConsumptionPerLtrMCHrs": 18.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B22060",
        "Equipment": "BULLDOZER D6 / EQUIVALENT",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 350000,
        "RatePerHr": 1346.15,
        "ConsumptionPerLtrMCHrs": 31.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B22080",
        "Equipment": "BULLDOZER D8 / EQUIVALENT",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 425000,
        "RatePerHr": 1634.62,
        "ConsumptionPerLtrMCHrs": 36.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B22090",
        "Equipment": "BULLDOZER D9 / EQUIVALENT",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 550000,
        "RatePerHr": 2115.38,
        "ConsumptionPerLtrMCHrs": 45.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A01100",
        "Equipment": "CONCRETE BATCH PLANT 100 M3 / HR",
        "TotalMCHrs": 0.19,
        "TotalNoOfDays": 0.02,
        "TotalNoOfMonths": 0.00,
        "MonthlyRent": 2500000,
        "RatePerHr": 9615.38,
        "ConsumptionPerLtrMCHrs": 0,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A01030",
        "Equipment": "CONCRETE BATCH PLANT 30 M3 / HR",
        "TotalMCHrs": 0.19,
        "TotalNoOfDays": 0.02,
        "TotalNoOfMonths": 0.00,
        "MonthlyRent": 750000,
        "RatePerHr": 2884.62,
        "ConsumptionPerLtrMCHrs": 0,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A01060",
        "Equipment": "CONCRETE BATCH PLANT 60 M3 / HR",
        "TotalMCHrs": 0.19,
        "TotalNoOfDays": 0.02,
        "TotalNoOfMonths": 0.00,
        "MonthlyRent": 950000,
        "RatePerHr": 3653.85,
        "ConsumptionPerLtrMCHrs": 0,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A01061",
        "Equipment": "CONCRETE LINING MACHINE",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 750000,
        "RatePerHr": 2884.62,
        "ConsumptionPerLtrMCHrs": 23.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "Mixer-1",
        "Equipment": "CONCRETE MIXER MACHINE",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 200000,
        "RatePerHr": 769.23,
        "ConsumptionPerLtrMCHrs": 3.75,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A15019",
        "Equipment": "CONCRETE PAVER 4m WIDE",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 2500000,
        "RatePerHr": 9615.38,
        "ConsumptionPerLtrMCHrs": 55.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A08110",
        "Equipment": "CONCRETE PUMP 60 ~ 110 M3 / HR",
        "TotalMCHrs": 1.27,
        "TotalNoOfDays": 0.16,
        "TotalNoOfMonths": 0.01,
        "MonthlyRent": 850000,
        "RatePerHr": 3269.23,
        "ConsumptionPerLtrMCHrs": 15.00,
        "TotalFuelInLtr": 19.11,
        "TotalAmount": 4739.52
    },
    {
        "Code": "FA02A10006",
        "Equipment": "CONCRETE TRANSIT MIXER MOBILE 6.0 M3",
        "TotalMCHrs": 3.82,
        "TotalNoOfDays": 0.48,
        "TotalNoOfMonths": 0.02,
        "MonthlyRent": 250000,
        "RatePerHr": 961.54,
        "ConsumptionPerLtrMCHrs": 8.00,
        "TotalFuelInLtr": 30.58,
        "TotalAmount": 7583.24
    },
    {
        "Code": "FA01A01028",
        "Equipment": "CRANE 28/33 TON TRUCK MOUNTED TELESCOPIC BOOM (28 TON)",
        "TotalMCHrs": 0.43,
        "TotalNoOfDays": 0.05,
        "TotalNoOfMonths": 0.00,
        "MonthlyRent": 350000,
        "RatePerHr": 1346.15,
        "ConsumptionPerLtrMCHrs": 7.00,
        "TotalFuelInLtr": 3.02,
        "TotalAmount": 747.80
    },
    {
        "Code": "FA01A01036",
        "Equipment": "CRANE 35 TON ROUGH TERRAIN TELESCOPIC BOOM",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 495000,
        "RatePerHr": 1903.85,
        "ConsumptionPerLtrMCHrs": 8.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A01045",
        "Equipment": "CRANE 45 TON TRUCK MOUNTED TELESCOPIC BOOM",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 625000,
        "RatePerHr": 2403.85,
        "ConsumptionPerLtrMCHrs": 9.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A01050",
        "Equipment": "CRANE 50 / 55 TON ROUGH TERRAIN TELESCOPIC BOOM (50 TON)",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 750000,
        "RatePerHr": 2884.62,
        "ConsumptionPerLtrMCHrs": 10.15,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A01051",
        "Equipment": "CRANE 50 TON CRAWLER LATTICE BOOM",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 675000,
        "RatePerHr": 2596.15,
        "ConsumptionPerLtrMCHrs": 9.62,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A01081",
        "Equipment": "CRANE 80 TON TRUCK MOUNTED TELESCOPIC BOOM",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 1100000,
        "RatePerHr": 4230.77,
        "ConsumptionPerLtrMCHrs": 10.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A01100",
        "Equipment": "CRANE 100 TON TRUCK MOUNTED TELESCOPIC BOOM",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 1450000,
        "RatePerHr": 5576.92,
        "ConsumptionPerLtrMCHrs": 12.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A01251",
        "Equipment": "CRANE 250 TON MAIN BOOM",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 3500000,
        "RatePerHr": 13461.54,
        "ConsumptionPerLtrMCHrs": 28.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A01001",
        "Equipment": "CRANE TOWER 1.0 (TIP) TON LIGHT DUTY",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 950000,
        "RatePerHr": 3653.85,
        "ConsumptionPerLtrMCHrs": 0,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A02001",
        "Equipment": "CRUSHER PLANT 200 TPH",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 3000000,
        "RatePerHr": 11538.46,
        "ConsumptionPerLtrMCHrs": 65.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B20012",
        "Equipment": "DUMP TRUCK 12 m3/18 Ton",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 250000,
        "RatePerHr": 961.54,
        "ConsumptionPerLtrMCHrs": 10.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B19225",
        "Equipment": "EXCAVATOR HITACHI ZX 210,240 / EQUIVALENT",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 325000,
        "RatePerHr": 1250.00,
        "ConsumptionPerLtrMCHrs": 23.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B19320",
        "Equipment": "EXCAVATOR HYUNDAI R360LC / EQUIVALENT",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 450000,
        "RatePerHr": 1730.77,
        "ConsumptionPerLtrMCHrs": 30.77,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A06006",
        "Equipment": "FORKLIFTER 6 TON",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 180000,
        "RatePerHr": 692.31,
        "ConsumptionPerLtrMCHrs": 5.50,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B18050",
        "Equipment": "FRONT END LOADER CAT950 / EQUIVALENT",
        "TotalMCHrs": 0.51,
        "TotalNoOfDays": 0.06,
        "TotalNoOfMonths": 0.00,
        "MonthlyRent": 250000,
        "RatePerHr": 961.54,
        "ConsumptionPerLtrMCHrs": 23.00,
        "TotalFuelInLtr": 11.72,
        "TotalAmount": 2906.91
    },
    {
        "Code": "FA02B21012",
        "Equipment": "MOTOR GRADER 12 FT BLADE",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 350000,
        "RatePerHr": 1346.15,
        "ConsumptionPerLtrMCHrs": 15.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01D25040",
        "Equipment": "PICK AWAY TRAILER / HIAB 10 TON 40-FT BED",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 325000,
        "RatePerHr": 1250.00,
        "ConsumptionPerLtrMCHrs": 4.62,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01D25020",
        "Equipment": "PICK AWAY TRUCK / HIAB 5 TON 20-FT BED",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 225000,
        "RatePerHr": 865.38,
        "ConsumptionPerLtrMCHrs": 4.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A04561",
        "Equipment": "PIPE LAYER CAT 561",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 750000,
        "RatePerHr": 2884.62,
        "ConsumptionPerLtrMCHrs": 25.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01A04572",
        "Equipment": "PIPE LAYER CAT 572",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 1200000,
        "RatePerHr": 4615.38,
        "ConsumptionPerLtrMCHrs": 30.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01C22200",
        "Equipment": "POWER GENERATOR 200 ~ 275 KVA (200 KVA) (Sound Proof)",
        "TotalMCHrs": 0.19,
        "TotalNoOfDays": 0.02,
        "TotalNoOfMonths": 0.00,
        "MonthlyRent": 250000,
        "RatePerHr": 961.54,
        "ConsumptionPerLtrMCHrs": 30.00,
        "TotalFuelInLtr": 5.73,
        "TotalAmount": 1421.86
    },
    {
        "Code": "FA01C22320",
        "Equipment": "POWER GENERATOR 320 ~ 365 KVA (320 KVA) (Sound Proof)",
        "TotalMCHrs": 0.19,
        "TotalNoOfDays": 0.02,
        "TotalNoOfMonths": 0.00,
        "MonthlyRent": 325000,
        "RatePerHr": 1250.00,
        "ConsumptionPerLtrMCHrs": 43.00,
        "TotalFuelInLtr": 8.22,
        "TotalAmount": 2038.00
    },
    {
        "Code": "FA01C22500",
        "Equipment": "POWER GENERATOR 500 KVA (Sound Proof)",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 495000,
        "RatePerHr": 1903.85,
        "ConsumptionPerLtrMCHrs": 53.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B25015",
        "Equipment": "ROLLER PNUEMATIC TYRE 15 / 18 TON (15 TON)",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 350000,
        "RatePerHr": 1346.15,
        "ConsumptionPerLtrMCHrs": 15.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B24001",
        "Equipment": "ROLLER VIBRATORY 1 TON",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 125000,
        "RatePerHr": 480.77,
        "ConsumptionPerLtrMCHrs": 1.50,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B24013",
        "Equipment": "ROLLER VIBRATORY 12.5 TON (PLANE)",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 275000,
        "RatePerHr": 1057.69,
        "ConsumptionPerLtrMCHrs": 12.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA03A21456",
        "Equipment": "SAND MAKER",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 650000,
        "RatePerHr": 2500.00,
        "ConsumptionPerLtrMCHrs": 35.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA03A21457",
        "Equipment": "SAND WASHER",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 950000,
        "RatePerHr": 3653.85,
        "ConsumptionPerLtrMCHrs": 50.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A03150",
        "Equipment": "SCREENING PLANT 150 TON / HR",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 1200000,
        "RatePerHr": 4615.38,
        "ConsumptionPerLtrMCHrs": 20.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B18131",
        "Equipment": "SKID STEER LOADER / BOBCAT",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 180000,
        "RatePerHr": 692.31,
        "ConsumptionPerLtrMCHrs": 5.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02A05022",
        "Equipment": "SLIP FORMING 22 MTR DIA",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 0,
        "RatePerHr": 0,
        "ConsumptionPerLtrMCHrs": 0,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA03A27022",
        "Equipment": "TANKER / BOUZER WATER 10000 LTR",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 250000,
        "RatePerHr": 961.54,
        "ConsumptionPerLtrMCHrs": 8.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B28078",
        "Equipment": "TRACTOR 78 HP",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 85000,
        "RatePerHr": 326.92,
        "ConsumptionPerLtrMCHrs": 3.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01D25041",
        "Equipment": "TRAILER FLAT BED 40 FT",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 150000,
        "RatePerHr": 576.92,
        "ConsumptionPerLtrMCHrs": 8.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01D25046",
        "Equipment": "TRAILER LOW BED 46 FT / 130 TON WITH PRIME MOVER",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 450000,
        "RatePerHr": 1730.77,
        "ConsumptionPerLtrMCHrs": 12.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA01D25037",
        "Equipment": "TRAILER SEMI LOWBED 37 FT / 75 TON WITH PRIME MOVER",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 425000,
        "RatePerHr": 1634.62,
        "ConsumptionPerLtrMCHrs": 12.00,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    },
    {
        "Code": "FA02B19340",
        "Equipment": "VIBRO HAMMER",
        "TotalMCHrs": 0,
        "TotalNoOfDays": 0,
        "TotalNoOfMonths": 0,
        "MonthlyRent": 0,
        "RatePerHr": 0,
        "ConsumptionPerLtrMCHrs": 0,
        "TotalFuelInLtr": 0,
        "TotalAmount": 0
    }
]

export default initialEquipmentData